# Generated by Django 4.0.4 on 2022-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shift", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="end_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
