# Generated by Django 4.0.4 on 2022-09-17 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 9, 17)),
        ),
    ]
